import type {
  AssetProvenance,
  CreditEntry,
} from '../src/content/types'
import type { LoadedAnimalDefinition } from './content-data'

function publishedZhCNName(
  definition: LoadedAnimalDefinition['definition'],
): string {
  if (definition.status !== 'published') {
    throw new Error(`草稿动物 “${definition.id}” 不能生成公开署名。`)
  }
  return definition.content['zh-CN'].name
}

function sourceTitle(record: AssetProvenance): string {
  return record.source.title
}

function sourceAuthor(record: AssetProvenance): string {
  switch (record.source.type) {
    case 'third-party':
      return record.source.author
    case 'generated':
      return record.source.tool
    case 'derived':
      return 'Prehistoric Animal Museum'
  }
}

function sourceUrl(record: AssetProvenance): string | undefined {
  return record.source.type === 'third-party'
    ? record.source.url
    : undefined
}

export function buildCreditEntries(
  packages: readonly LoadedAnimalDefinition[],
): CreditEntry[] {
  return packages
    .filter(({ definition }) => definition.status === 'published')
    .flatMap(({ definition }) =>
      [...definition.provenance]
        .sort((left, right) =>
          left.assetPath < right.assetPath
            ? -1
            : left.assetPath > right.assetPath
              ? 1
              : 0,
        )
        .map((record) => {
          const url = sourceUrl(record)
          return {
            id: `${definition.id}:${record.assetPath}`,
            animalId: definition.id,
            assetPath: record.assetPath,
            assetKind: record.kind,
            sourceTitle: sourceTitle(record),
            author: sourceAuthor(record),
            licenseName: record.license.name,
            licenseUrl: record.license.url,
            ...(url === undefined ? {} : { sourceUrl: url }),
            attribution: record.attribution,
            modifications: record.modifications,
          }
        }),
    )
}

export function renderCreditsModule(
  packages: readonly LoadedAnimalDefinition[],
): string {
  const entries = buildCreditEntries(packages)
  return `// Generated by npm run generate:credits. Do not edit by hand.
import type { CreditEntry } from './types'

export const credits = ${JSON.stringify(entries, null, 2)} as const satisfies readonly CreditEntry[]
`
}

function sourceLine(record: AssetProvenance): string {
  if (record.source.type === 'third-party') {
    return `[${record.source.title}](${record.source.url}) by ${record.source.author}`
  }
  if (record.source.type === 'generated') {
    return `${record.source.title}, generated with ${record.source.tool} on ${record.source.generatedOn}`
  }
  return `${record.source.title}, derived on ${record.source.generatedOn}`
}

export function renderThirdPartyNotices(
  packages: readonly LoadedAnimalDefinition[],
): string {
  const sections = packages
    .filter(({ definition }) => definition.status === 'published')
    .map(({ definition }) => {
      const records = [...definition.provenance]
        .sort((left, right) =>
          left.assetPath < right.assetPath
            ? -1
            : left.assetPath > right.assetPath
              ? 1
              : 0,
        )
        .map(
          (record) => `### \`${record.assetPath}\`

- Asset type: ${record.kind}
- Source: ${sourceLine(record)}
- License: [${record.license.name}](${record.license.url})
- Attribution: ${record.attribution}
- Runtime SHA-256: \`${record.runtime.sha256}\`
- Modifications:
${record.modifications.map((change) => `  - ${change}`).join('\n')}`,
        )
        .join('\n')

      return `## ${publishedZhCNName(definition)} (\`${definition.id}\`)

${records}`
    })
    .join('\n')

  return `# Third-party notices

This file is generated from the typed animal-package provenance records by
\`npm run generate:credits\`. Do not edit it independently. Code, original
content, contributions, and Brand Assets follow the separate scopes in
[LICENSING.md](LICENSING.md).

## Bundled runtime libraries

- **React 19.2.8**, **React DOM 19.2.8**, and **Scheduler 0.27.0** —
  Copyright (c) Meta Platforms, Inc. and affiliates.
  Distributed under the [MIT License](LICENSES/React-MIT.txt).
- **Three.js 0.185.1** — Copyright (c) 2010-2026 three.js authors.
  Distributed under the [MIT License](LICENSES/Three.js-MIT.txt).
- **Lucide React 1.27.0** — Copyright (c) 2026 Lucide Contributors.
  Distributed under the [ISC License](LICENSES/Lucide-ISC.txt); portions
  derived from Feather are retained under the MIT License in the same file.

## Bundled fonts

- **ZCOOL KuaiLe** — Copyright 2018 The ZCOOL KuaiLe Project Authors.
  Bundled from \`@fontsource/zcool-kuaile@5.3.0\` under the
  [SIL Open Font License 1.1](LICENSES/OFL-1.1.txt).
- **Noto Sans SC** — Copyright Google Inc.
  Bundled from \`@fontsource-variable/noto-sans-sc@5.3.0\` under the
  [SIL Open Font License 1.1](LICENSES/OFL-1.1.txt).

## Scale encounter music

- **RPG Town** — Copyright Karate Studios. Bundled as the optional pastoral
  exploration music for the “Compare” encounter under
  [Creative Commons CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/).
  Source: [OpenGameArt](https://opengameart.org/content/2-whimsical-rpg-themes).
  The source FLAC was crossfaded into a seamless loop, loudness-normalized,
  and encoded as Ogg Vorbis. Runtime SHA-256:
  \`79d427b3d82a6d73b560eb01f3b62ba1b014b718b2ff68724aee446e7d1c497d\`.

${sections}
`
}
